#!/usr/bin/env python

import os
import sys

# get directories in the "folder" in alphabetical order
def listdirs(folder):
  result = []
  for d in os.listdir(folder):
    if os.path.isdir(os.path.join(folder, d)): result.append(os.path.join(folder, d))
  result.sort()
  return result

# set location of unit tests and source dir
source_dir  = sys.argv[1]
unit_test_dir = source_dir + '/external/unit-tests'

# open file for gathering unit tests
cmake_path = os.path.realpath(__file__)[:-19]
f = open(cmake_path + 'autogenerated/UnitTests.cmake', 'w')

# gather unit tests
for subd in listdirs(unit_test_dir):
  if not '.git' in subd:
    for path in listdirs(subd):
      if os.path.isdir(path):
        if os.path.isfile(path + '/test.F90'):
          name = path.split('/')[-2] + '__' + path.split('/')[-1]
          f.write('add_unit_test(%s %s)\n' % (path, name))

f.close()
